name: cc206_emoti_sense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  audioplayers: ^6.1.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/Gotham Regular.otf
        - asset: assets/Gotham Bold.otf
        - asset: assets/Gotham Medium.otf
          weight: 700
